#!/bin/bash -e

mkdir -p datatooltk
cp ../dist/* datatooltk
mkdir -p source/datatooltk/src
cd ../src
tar cvf ../ctan/source/datatooltk/src/tmp.tar `git ls-files` 
cd ../ctan/source/datatooltk/src
tar xvf tmp.tar
rm tmp.tar
cd ../../..
cp ../README source/datatooltk
zip -r datatooltk.tds.zip source
zip -r datatool.zip datatooltk datatooltk.tds.zip
