#!/usr/bin/bash

datatooltk --output-format dbtex-2 --nomap-tex-specials --nocsv-escape --csv sample-1000x3.csv --filter Field1 eq grammatically -o data.dbtex || exit $?
pdflatex -jobname test-dbtex-single-doc1 test-dbtex-single-doc
