#!/usr/bin/bash

datatooltk --output-format dbtex-2 --nomap-tex-specials --nocsv-escape --csv-sep ',' --sort Field1 --sort-locale en-GB --csv sample-1000x3-utf8.csv -o data.dbtex || exit $?
pdflatex -jobname test-dbtex-utf8-doc1 test-dbtex-utf8-doc
