#!/usr/bin/bash

datatooltk --output-format dbtex-2 --nomap-tex-specials --nocsv-escape --sort Field1 --sort-locale none --sort-case-insensitive --csv sample-1000x3.csv -o data.dbtex || exit $?
pdflatex -jobname test-dbtex-doc2 test-dbtex-doc
