#!/usr/bin/bash

datatooltk --output-format dbtex-2 --nomap-tex-specials --nocsv-escape --csv-sep ',' --csv sample-1000x3.csv -o data.dbtex || exit $?
pdflatex -jobname test-dbtex-doc1 test-dbtex-doc
