#!/usr/bin/bash

datatooltk --output-format dbtex-2 --nomap-tex-specials --nocsv-escape --csv-sep ',' --csv sample-1000x6.csv -o data.dbtex --remove-columns "4-" || exit $?
pdflatex -jobname test-dbtex-1000x6-doc8 test-dbtex-doc
