#!/usr/bin/bash

datatooltk --output-format dbtex-2 --map-tex-specials --csv-escape '\' --sort Field1 --sort-locale en-GB --csv sample-1000x3-utf8-spchar.csv -o data.dbtex || exit $?
pdflatex -jobname test-dbtex-utf8-doc2 test-dbtex-utf8-doc
