#!/usr/bin/perl -w

use strict;
use warnings;

if ($#ARGV < 1)
{
   die "Syntax: $0 <rows> <col1_type> <col2_type> ...\n";
}

my $row_count = shift(@ARGV);

my @col_types = ();

foreach my $type (@ARGV)
{
   if ($type eq 'int' or $type eq 'integer')
   {
      push @col_types, 1;
   }
   elsif ($type eq 'decimal' or $type eq 'real')
   {
      push @col_types, 2;
   }
   elsif ($type eq 'currency')
   {
      push @col_types, 3;
   }
   elsif ($type eq 'si')
   {
      push @col_types, 4;
   }
   else
   {
      die "Unknown column type '$type'\n";
   }
}

my $col_count = $#col_types+1;

for (my $col = 1; $col <= $col_count; $col++)
{
   print "Field", $col, $col == $col_count ? "\n" : ",";
}

for (my $row = 1; $row <= $row_count; $row++)
{
   for (my $col = 1; $col <= $col_count; $col++)
   {
      my $val;

      if ($col_types[$col-1] == 1)
      {
         $val = int(rand(10000)) - 5000;
      }
      else
      {
         $val = rand(10000) - 5000.0;

         if ($col_types[$col-1] == 3)
         {
            $val = sprintf "\\\$%.2f", $val;
         }
         elsif ($col_types[$col-1] == 4)
         {
            $val = sprintf "%e", $val;
         }
      }

      print $val, $col == $col_count ? "\n" : ",";
   }
}

1;
