#!/usr/bin/bash

function build
{
  filename=$1

  /usr/bin/time -f "$filename:\t%e\t%E" --append --output=$logfile $filename  || exit $?
}

logfile='runtest.log'

rm -f $logfile
touch $logfile

for file in buildtest-csv-doc*; do
 [ -e "$file" ] || continue
 build $file
done

for file in buildtest-newdb-doc*; do
 [ -e "$file" ] || continue
 build $file
done

for file in buildtest-dbtex-doc*; do
 [ -e "$file" ] || continue
 build $file
done

for file in buildtest-csv-utf8-doc*; do
 [ -e "$file" ] || continue
 build $file
done

for file in buildtest-dbtex-utf8-doc*; do
 [ -e "$file" ] || continue
 build $file
done

for file in buildtest-*-filter-doc*; do
 [ -e "$file" ] || continue
 build $file
done

for file in buildtest-*-single-doc*; do
 [ -e "$file" ] || continue
 build $file
done

for file in buildtest-csv-*x*-doc*; do
 [ -e "$file" ] || continue
 build $file
done

for file in buildtest-newdb-*x*-doc*; do
 [ -e "$file" ] || continue
 build $file
done

for file in buildtest-dbtex-*x*-doc*; do
 [ -e "$file" ] || continue
 build $file
done

for file in buildtest-iter-*-doc*; do
 [ -e "$file" ] || continue
 build $file
done


