#!/usr/bin/perl -w

use warn;
use strict;
use XML::LibXML;

my $dictdir = '../resources/dictionaries';
my $mainclass = '../src/DatatoolTk.java';

unless ($#ARGV > 1 || $#ARGV < 0)
{
   die "Syntax: $0 <lang> [<region>]";
}

1;
