USE samples;
INSERT INTO words (Word) VALUES ('minnow');
INSERT INTO words (Word) VALUES ('running board');
INSERT INTO words (Word) VALUES ('dispirit');
INSERT INTO words (Word) VALUES ('gravelly');
INSERT INTO words (Word) VALUES ('sharp-tongued');
INSERT INTO words (Word) VALUES ('penitentiary');
INSERT INTO words (Word) VALUES ('vice');
INSERT INTO words (Word) VALUES ('witness box');
INSERT INTO words (Word) VALUES ('hydrochloric acid');
INSERT INTO words (Word) VALUES ('disclosure');
INSERT INTO words (Word) VALUES ('inscribe');
INSERT INTO words (Word) VALUES ('parch');
INSERT INTO words (Word) VALUES ('bridesmaid');
INSERT INTO words (Word) VALUES ('android');
INSERT INTO words (Word) VALUES ('newspeak');
INSERT INTO words (Word) VALUES ('sambuca');
INSERT INTO words (Word) VALUES ('uncontrollable');
INSERT INTO words (Word) VALUES ('garret');
INSERT INTO words (Word) VALUES ('bovine spongiform encephalopathy');
INSERT INTO words (Word) VALUES ('risk captial');
INSERT INTO words (Word) VALUES ('stipple');
INSERT INTO words (Word) VALUES ('goggle');
INSERT INTO words (Word) VALUES ('cutlass');
INSERT INTO words (Word) VALUES ('Somali');
INSERT INTO words (Word) VALUES ('letter');
INSERT INTO words (Word) VALUES ('dreamboat');
INSERT INTO words (Word) VALUES ('pear drop');
INSERT INTO words (Word) VALUES ('night school');
INSERT INTO words (Word) VALUES ('translocate');
INSERT INTO words (Word) VALUES ('Proven\c{c}al');
INSERT INTO words (Word) VALUES ('effective');
INSERT INTO words (Word) VALUES ('English');
INSERT INTO words (Word) VALUES ('bruiser');
INSERT INTO words (Word) VALUES ('green woodpecker');
INSERT INTO words (Word) VALUES ('yoke');
INSERT INTO words (Word) VALUES ('sort');
INSERT INTO words (Word) VALUES ('zookeeper');
INSERT INTO words (Word) VALUES ('Stalinism');
INSERT INTO words (Word) VALUES ('placid');
INSERT INTO words (Word) VALUES ('made-up');
INSERT INTO words (Word) VALUES ('sae');
INSERT INTO words (Word) VALUES ('entertain');
INSERT INTO words (Word) VALUES ('clapperboard');
INSERT INTO words (Word) VALUES ('fanatic');
INSERT INTO words (Word) VALUES ('plumb');
INSERT INTO words (Word) VALUES ('tournament');
INSERT INTO words (Word) VALUES ('pleat');
INSERT INTO words (Word) VALUES ('pertain');
INSERT INTO words (Word) VALUES ('vocal');
INSERT INTO words (Word) VALUES ('peradventure');
INSERT INTO words (Word) VALUES ('non-existent');
INSERT INTO words (Word) VALUES ('diamant\\\'e');
INSERT INTO words (Word) VALUES ('chard');
INSERT INTO words (Word) VALUES ('pause');
INSERT INTO words (Word) VALUES ('raw material');
INSERT INTO words (Word) VALUES ('specs');
INSERT INTO words (Word) VALUES ('gage');
INSERT INTO words (Word) VALUES ('advert');
INSERT INTO words (Word) VALUES ('banger');
INSERT INTO words (Word) VALUES ('carton');
INSERT INTO words (Word) VALUES ('decimal point');
INSERT INTO words (Word) VALUES ('broadleaved');
INSERT INTO words (Word) VALUES ('imaginings');
INSERT INTO words (Word) VALUES ('negative equity');
INSERT INTO words (Word) VALUES ('recant');
INSERT INTO words (Word) VALUES ('HTTP');
INSERT INTO words (Word) VALUES ('comeback');
INSERT INTO words (Word) VALUES ('psychiatrist');
INSERT INTO words (Word) VALUES ('sorry');
INSERT INTO words (Word) VALUES ('filename');
INSERT INTO words (Word) VALUES ('cloven hoof');
INSERT INTO words (Word) VALUES ('proselytize');
INSERT INTO words (Word) VALUES ('equestrian');
INSERT INTO words (Word) VALUES ('broadloom');
INSERT INTO words (Word) VALUES ('parry');
INSERT INTO words (Word) VALUES ('sum');
INSERT INTO words (Word) VALUES ('trackball');
INSERT INTO words (Word) VALUES ('versed');
INSERT INTO words (Word) VALUES ('m\\\'etier');
INSERT INTO words (Word) VALUES ('felicity');
INSERT INTO words (Word) VALUES ('campery');
INSERT INTO words (Word) VALUES ('outside interest');
INSERT INTO words (Word) VALUES ('see-saw');
INSERT INTO words (Word) VALUES ('string course');
INSERT INTO words (Word) VALUES ('guelder rose');
INSERT INTO words (Word) VALUES ('sloe');
INSERT INTO words (Word) VALUES ('czar');
INSERT INTO words (Word) VALUES ('clearing house');
INSERT INTO words (Word) VALUES ('object');
INSERT INTO words (Word) VALUES ('loan shark');
INSERT INTO words (Word) VALUES ('smacker');
INSERT INTO words (Word) VALUES ('kill');
INSERT INTO words (Word) VALUES ('currently');
INSERT INTO words (Word) VALUES ('rugby league');
INSERT INTO words (Word) VALUES ('dwarfism');
INSERT INTO words (Word) VALUES ('salary');
INSERT INTO words (Word) VALUES ('royal jelly');
INSERT INTO words (Word) VALUES ('gatefold');
INSERT INTO words (Word) VALUES ('charpoy');
INSERT INTO words (Word) VALUES ('maxwell');
